
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ai_readiness'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'ai_readiness'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]       # SQL transformations
analysis-paths: ["analyses"]  #
test-paths: ["tests"]         # Data quality checks
seed-paths: ["seeds"]         # CSV files loaded into the warehouse
macro-paths: ["macros"]       # Reusable SQL logic
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
# Configuring models
models:
  ai_readiness:
    +materialized: view

# Configuring seeds
seeds:
  ai_readiness:
    +quote_columns: false

semantic-models:
  time_spine:
    model: ref('time_spine')
    primary_column: date_day